CREATE TABLE auctions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id            BIGINT NOT NULL UNIQUE REFERENCES listings(id) ON DELETE CASCADE,
    start_price           NUMERIC(14,2) NOT NULL CHECK (start_price >= 0),
    current_price         NUMERIC(14,2) NOT NULL CHECK (current_price >= 0),
    minimum_bid_increment NUMERIC(14,2) NOT NULL DEFAULT 1.00 CHECK (minimum_bid_increment > 0),
    leader_id             BIGINT REFERENCES users(id) ON DELETE SET NULL,
    bids_count            INT    NOT NULL DEFAULT 0,
    start_at              TIMESTAMPTZ NOT NULL,
    end_at                TIMESTAMPTZ NOT NULL,
    status                TEXT   NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending','active','finished','cancelled')),
    winner_id             BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (end_at > start_at)
);
CREATE INDEX idx_auctions_status ON auctions(status);
CREATE INDEX idx_auctions_end    ON auctions(end_at) WHERE status = 'active';

CREATE TABLE bids (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id      BIGINT NOT NULL REFERENCES auctions(id) ON DELETE CASCADE,
    bidder_id       BIGINT NOT NULL REFERENCES users(id)    ON DELETE RESTRICT,
    amount          NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    idempotency_key TEXT UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_bids_auction ON bids(auction_id, amount DESC);
CREATE INDEX idx_bids_bidder  ON bids(bidder_id);