CREATE TABLE listings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id     BIGINT NOT NULL REFERENCES users(id)      ON DELETE RESTRICT,
    title         TEXT   NOT NULL,
    description   TEXT,
    category_id   INT    REFERENCES categories(id) ON DELETE SET NULL,
    brand_id      INT    REFERENCES brands(id)     ON DELETE SET NULL,
    collection_id INT    REFERENCES collections(id) ON DELETE SET NULL,
    size          TEXT,
    color         TEXT,
    condition     TEXT,
    sale_type     TEXT   NOT NULL DEFAULT 'fixed_price'
                  CHECK (sale_type IN ('fixed_price','auction')),
    price         NUMERIC(14,2) NOT NULL CHECK (price >= 0),
    status        TEXT   NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft','on_moderation','active','rejected','sold','archived')),
    search_vector TSVECTOR,
    published_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_listings_seller   ON listings(seller_id);
CREATE INDEX idx_listings_category ON listings(category_id);
CREATE INDEX idx_listings_brand    ON listings(brand_id);
CREATE INDEX idx_listings_status   ON listings(status);
CREATE INDEX idx_listings_search   ON listings USING GIN (search_vector);

CREATE TABLE listing_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    storage_key TEXT   NOT NULL,
    sha256      TEXT,
    position    INT    NOT NULL DEFAULT 0,
    size_bytes  INT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (listing_id, position)
);
CREATE INDEX idx_listing_images_listing ON listing_images(listing_id);