CREATE TABLE moderation_reviews (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id   BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    moderator_id BIGINT NOT NULL REFERENCES users(id)    ON DELETE RESTRICT,
    decision     TEXT   NOT NULL CHECK (decision IN ('approved','rejected')),
    comment      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_moderation_listing   ON moderation_reviews(listing_id);
CREATE INDEX idx_moderation_moderator ON moderation_reviews(moderator_id);