CREATE TABLE categories (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE brands (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE collections (
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id INT  NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
    name     TEXT NOT NULL,
    year     INT,
    UNIQUE (brand_id, name)
);
CREATE INDEX idx_collections_brand ON collections(brand_id);