CREATE TABLE wallet_transactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    order_id   BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    kind       TEXT   NOT NULL
               CHECK (kind IN ('deposit','withdrawal','escrow_hold',
                               'escrow_release','refund','payout')),
    amount     NUMERIC(14,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_wallet_tx_user  ON wallet_transactions(user_id, created_at DESC);
CREATE INDEX idx_wallet_tx_order ON wallet_transactions(order_id);